version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dmf
      POSTGRES_PASSWORD: dmf
      POSTGRES_DB: dmf
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio:/data

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports: ["9200:9200","9600:9600"]
    ulimits:
      memlock:
        soft: -1
        hard: -1

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  gateway:
    build:
      context: ../../..
      dockerfile: deploy/docker/gateway.Dockerfile
    environment:
      DMF_ENV: dev
      GATEWAY_PORT: "8080"
    ports: ["8080:8080"]
    depends_on:
      - postgres
      - opensearch

  dms:
    build:
      context: ../../..
      dockerfile: deploy/docker/dms.Dockerfile
    environment:
      DMF_ENV: dev
      DATABASE_URL: postgresql+psycopg://dmf:dmf@postgres:5432/dmf
      OPENSEARCH_URL: http://opensearch:9200
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: dmf-dev
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      UVICORN_PORT: "8081"
    ports: ["8081:8081"]
    depends_on:
      - postgres
      - minio
      - opensearch

volumes:
  pgdata:
  minio:
